In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_excel("77countries.xlsx")
#df=df[0:30]
#State=df.State.unique()
#df_last_date=df[df['date']=="2020-09-03"]

In [4]:
df

continent        location  total_deaths        R0  total_cases  \
0   North America   United States        185744  2.465409      6114406   
1   South America          Brazil        123780  2.000668      3997865   
2            Asia           India         67376  1.731947      3853406   
3   North America          Mexico         65816  1.800513       610957   
4          Europe  United Kingdom         41514  2.042228       338676   
..            ...             ...           ...       ...          ...   
72         Europe         Albania           296  2.268620         9728   
73         Africa          Zambia           292  1.908191        12415   
74         Africa         Senegal           287  1.453346        13743   
75         Africa           Ghana           276  2.037094        44658   
76         Europe          Greece           273  3.141513        10757   

    new_cases  population  population_density  median_age  aged_65_older  \
0       38754   331002647              35.608        38.3         15.413   
1       46934   212559409              25.040        33.5          8.552   
2       83883  1380004385             450.419        28.2          5.989   
3        4921   128932753              66.444        29.3          6.857   
4        1508    67886004             272.898        40.8         18.517   
..        ...         ...                 ...         ...            ...   
72        122     2877800             104.871        38.0         13.188   
73         34    18383956              22.995        17.7          2.480   
74         75    16743930              82.328        18.7          3.008   
75        198    31072945             126.719        21.1          3.385   
76        233    10423056              83.479        45.3         20.396   

    aged_70_older  gdp_per_capita  extreme_poverty  cardiovasc_death_rate  \
0           9.732       54225.446              1.2                151.089   
1           5.060       14103.452              3.4                177.961   
2           3.414        6426.674             21.2                282.280   
3           4.321       17336.469              2.5                152.783   
4          12.527       39753.244              0.2                122.137   
..            ...             ...              ...                    ...   
72          8.643       11803.431              1.1                304.195   
73          1.542        3689.251             57.5                234.499   
74          1.796        2470.580             38.0                241.219   
75          1.948        4227.630             12.0                298.245   
76         14.524       24574.382              1.5                175.695   

    diabetes_prevalence  female_smokers  male_smokers  \
0                 10.79            19.1          24.6   
1                  8.11            10.1          17.9   
2                 10.39             1.9          20.6   
3                 13.06             6.9          21.4   
4                  4.28            20.0          24.7   
..                  ...             ...           ...   
72                10.08             7.1          51.2   
73                 3.94             3.1          24.7   
74                 2.42             0.4          16.6   
75                 4.97             0.3           7.7   
76                 4.55            35.3          52.0   

    hospital_beds_per_thousand  life_expectancy  
0                         2.77            78.86  
1                         2.20            75.88  
2                         0.53            69.66  
3                         1.38            75.05  
4                         2.54            81.32  
..                         ...              ...  
72                        2.89            78.57  
73                        2.00            63.89  
74                         NaN            67.94  
75                        0.90            64.07  
76                        4.21            82.2

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   continent                   77 non-null     object 
 1   location                    77 non-null     object 
 2   total_deaths                77 non-null     int64  
 3   R0                          77 non-null     float64
 4   total_cases                 77 non-null     int64  
 5   new_cases                   77 non-null     int64  
 6   population                  77 non-null     int64  
 7   population_density          77 non-null     float64
 8   median_age                  77 non-null     float64
 9   aged_65_older               77 non-null     float64
 10  aged_70_older               76 non-null     float64
 11  gdp_per_capita              77 non-null     float64
 12  extreme_poverty             58 non-null     float64
 13  cardiovasc_death_rate       77 non-nu

In [6]:
#Filling missing values

In [7]:
l=df.columns
l

Index(['continent', 'location', 'total_deaths', 'R0', 'total_cases',
       'new_cases', 'population', 'population_density', 'median_age',
       'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'hospital_beds_per_thousand', 'life_expectancy'],
      dtype='object')

In [8]:
df.dropna(inplace=True)

In [9]:
df

continent                location  total_deaths        R0  \
0   North America           United States        185744  2.465409   
1   South America                  Brazil        123780  2.000668   
2            Asia                   India         67376  1.731947   
3   North America                  Mexico         65816  1.800513   
4          Europe          United Kingdom         41514  2.042228   
5          Europe                   Italy         35497  4.184995   
8            Asia                    Iran         21797  1.532991   
9   South America                Colombia         20348  1.991294   
10         Europe                  Russia         17414  2.716937   
11         Africa            South Africa         14389  1.761732   
12  South America                   Chile         11344  2.250374   
13         Europe                 Belgium          9898  3.598751   
15  North America                  Canada          9135  2.764913   
16  South America               Argentina          8971  2.114039   
17           Asia               Indonesia          7616  2.023743   
19  South America                 Ecuador          6619  1.872841   
20           Asia                  Turkey          6462  1.711242   
21           Asia                Pakistan          6328  1.362303   
23         Europe                  Sweden          5820  3.206547   
24         Africa                   Egypt          5461  1.434267   
26           Asia                   China          4727  2.436220   
27           Asia              Bangladesh          4351  1.618151   
29         Europe                 Romania          3721  2.701301   
32         Europe                 Ukraine          2656  3.038230   
34  North America                  Panama          2030  1.823209   
36           Asia              Kazakhstan          1889  2.260230   
37         Europe                Portugal          1827  3.112976   
38         Europe                 Ireland          1777  2.265882   
39  North America      Dominican Republic          1765  1.846620   
41         Africa                 Algeria          1525  1.359804   
43         Africa                 Morocco          1216  1.656326   
44           Asia              Kyrgyzstan          1059  1.737408   
46           Asia                  Israel           969  2.094296   
47           Asia                 Armenia           884  2.455895   
48         Africa                Ethiopia           846  2.061205   
49  North America             El Salvador           739  1.807100   
50         Europe                 Austria           734  3.014221   
54        Oceania               Australia           663  2.555908   
55         Europe                Bulgaria           642  3.516514   
56         Europe  Bosnia and Herzegovina           627  2.773516   
57         Europe                 Denmark           626  3.178221   
58         Europe                 Hungary           619  3.091244   
59         Africa                   Kenya           577  1.662634   
60           Asia                   Yemen           571  1.062837   
63  North America              Costa Rica           453  1.959368   
68  South America                Paraguay           358  1.888903   
70           Asia             South Korea           329  2.660926   
72         Europe                 Albania           296  2.268620   
73         Africa                  Zambia           292  1.908191   
75         Africa                   Ghana           276  2.037094   
76         Europe                  Greece           273  3.141513   

    total_cases  new_cases  population  population_density  median_age  \
0       6114406      38754   331002647              35.608        38.3   
1       3997865      46934   212559409              25.040        33.5   
2       3853406      83883  1380004385             450.419        28.2   
3        610957       4921   128932753              66.444        29.3   
4        338676       1508    67886004           

In [10]:
df_numerical=df.iloc[:,2:]

In [11]:
df_numerical.shape

(51, 17)

### Using only Elasticnet regression

In [12]:
df_numerical.drop(['new_cases'],axis=1,inplace=True)

In [13]:

y_train_reg = df_numerical['total_cases']
x_train_reg = df_numerical.drop('total_cases',axis=1)
x_test=x_train_reg.iloc[2:3,:]

In [14]:
from sklearn.linear_model import HuberRegressor
from sklearn import linear_model
ridge_reg = linear_model.Ridge(alpha=.5)
ridge_reg.fit(x_train_reg,y_train_reg)

Ridge(alpha=0.5)

In [57]:
ridge_reg.predict(x_test)

array([73006.9691871])

In [53]:
lm=LinearRegression()

In [54]:
lm.fit(x_train_reg,y_train_reg)

LinearRegression()

In [55]:
lm.predict(x_test)

array([73101.45170621])

In [99]:
coeff=en_reg.coef_

In [100]:
intercept=en_reg.intercept_

In [101]:
def dictionary(df,location):
    df_location=df[df['location']==location]
    df_location=df_location.iloc[:,3:]
    df_location_dict=df_location.to_dict('records')
    
    return df_location_dict
    
    

In [102]:
location="India"
df_location_dict=dictionary(df,location)

In [103]:
death=inter
k=0
for i in df_location_dict[0].values():
    death=death+(i*coeff[k])
    k=k+1

In [105]:
death

71241.1945330599

In [24]:
from sklearn.linear_model import ElasticNet


In [16]:
lasso_reg = linear_model.Lasso(alpha=0.1)
lasso_reg.fit(x_train_reg,y_train_reg)

lasso_reg.predict(x_test)

array([2983815.35550532])

In [25]:
en_reg = ElasticNet(random_state=0)
en_reg.fit(x_train_reg,y_train_reg)

en_reg.predict(x_test)

array([3003231.25668595])

In [94]:
en_reg.coef_[0]

-26.200453728402575

In [89]:
en_reg.intercept_

-6924.314960388718

In [90]:
en_reg.n_features_in_

16

In [23]:
x_train_reg.columns

Index(['total_deaths', 'R0', 'population', 'population_density', 'median_age',
       'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'hospital_beds_per_thousand', 'life_expectancy'],
      dtype='object')

In [19]:
x_train_reg.iloc[2:3,:]

total_deaths        R0  population  population_density  median_age  \
2         67376  1.731947  1380004385             450.419        28.2   

   aged_65_older  aged_70_older  gdp_per_capita  extreme_poverty  \
2          5.989          3.414        6426.674             21.2   

   cardiovasc_death_rate  diabetes_prevalence  female_smokers  male_smokers  \
2                 282.28                10.39             1.9          20.6   

   hospital_beds_per_thousand  life_expectancy  
2                        0.53            69.66

In [22]:
R0=1.731947
total_cases=3853406
new_cases=83883
population=1380004385
population_density=450.419
median_age=28.2
aged_65_older=5.989
aged_70_older=3.414
gdp_per_capita=6426.674
extreme_poverty=21.2
cardiovasc_death_rate=282.28
diabetes_prevalence=10.39
female_smokers=1.9
male_smokers=20.6
hospital_beds_per_thousand=0.53
life_expectancy=69.66


In [21]:
intercept=en_reg.intercept_
R0_coef=en_reg.coef_[0]
total_cases_coef=en_reg.coef_[1]
new_cases_coef=en_reg.coef_[2]
population_coef=en_reg.coef_[3]
population_density_coef=en_reg.coef_[4]
median_age_coef=en_reg.coef_[5]
aged_65_older_coef=en_reg.coef_[6]
aged_70_older_coef=en_reg.coef_[7]
gdp_per_capita_coef=en_reg.coef_[8]
extreme_poverty_coef=en_reg.coef_[9]
cardiovasc_death_rate_coef=en_reg.coef_[10]
diabetes_prevalence_coef=en_reg.coef_[11]
female_smokers_coef=en_reg.coef_[12]
male_smokers_coef=en_reg.coef_[13]
hospital_beds_per_thousand_coef=en_reg.coef_[14]
life_expectancy_coef=en_reg.coef_[15]


IndexError: index 15 is out of bounds for axis 0 with size 15

In [115]:
diabetes_prevalence_coef
hospital_beds_per_thousand_coef
median_age_coef
total_cases_coef
aged_70_older_coef
extreme_poverty_coef
female_smokers_coef
male_smokers_coef
R0_coef

410.930002769215

In [20]:
median_age_coef

NameError: name 'median_age_coef' is not defined

In [97]:
death=intercept+(R0_coef*R0)+(total_cases_coef*total_cases)+(new_cases_coef*new_cases)+(population_coef*population)+(population_density_coef*population_density)+(median_age_coef*median_age)+(aged_65_older_coef*aged_65_older)+(aged_70_older_coef*aged_70_older)+(gdp_per_capita_coef*gdp_per_capita)+(extreme_poverty_coef*extreme_poverty)+(cardiovasc_death_rate_coef*cardiovasc_death_rate)+(diabetes_prevalence_coef*diabetes_prevalence)+(female_smokers_coef*female_smokers)+(male_smokers_coef*male_smokers)+(hospital_beds_per_thousand_coef*hospital_beds_per_thousand)+(life_expectancy_coef*life_expectancy)

In [98]:
death

72393.51183923168

In [109]:
en_reg.coef_

array([-2.62004537e+01,  3.60584668e-02, -8.06213173e-01, -2.18981243e-06,
       -2.99663967e+00,  4.10930003e+02, -3.72163973e+02,  7.08752062e+02,
       -7.54569970e-02, -1.72813896e+01, -1.30774630e+01,  3.76619160e+02,
       -1.49054329e+02, -8.97911126e+01, -7.58936357e+02,  5.45567485e+01])